{
 "4.0.8": {
  "meta": {
   "description": "Exception interfaces and implementations",
   "homepage": "https://pypi.python.org/pypi/zope.exceptions",
   "license": {
    "fullName": "Zope Public License 2.0",
    "shortName": "zpl20",
    "spdxId": "ZPL-2.0",
    "url": "http://spdx.org/licenses/ZPL-2.0.html"
   },
   "long_description": "",
   "maintainers": [
    {
     "email": "cillian.deroiste@gmail.com",
     "github": "cillianderoiste",
     "name": "Cillian de R\u00f3iste"
    }
   ],
   "name": "python3.7-zope.exceptions",
   "platforms": [
    {
     "kernel": {
      "_type": "kernel",
      "execFormat": {
       "_type": "exec-format",
       "name": "elf"
      },
      "families": {},
      "name": "linux"
     }
    },
    {
     "kernel": {
      "families": {
       "darwin": {
        "_type": "exec-format",
        "name": "darwin"
       }
      }
     }
    }
   ],
   "position": "pkgs/development/python-modules/zope_exceptions/default.nix:22"
  },
  "revs": [
   "00005ce0bdbc3c13804adc9a7fd71a02cc0b8db2",
   "427218836457753db735b45b270411ecbf0ee697"
  ]
 },
 "4.3": {
  "meta": {
   "description": "Exception interfaces and implementations",
   "homepage": "https://pypi.python.org/pypi/zope.exceptions",
   "license": {
    "fullName": "Zope Public License 2.0",
    "shortName": "zpl20",
    "spdxId": "ZPL-2.0",
    "url": "http://spdx.org/licenses/ZPL-2.0.html"
   },
   "long_description": "",
   "maintainers": [
    {
     "email": "cillian.deroiste@gmail.com",
     "github": "cillianderoiste",
     "name": "Cillian de R\u00f3iste"
    }
   ],
   "name": "python3.7-zope.exceptions",
   "platforms": [
    {
     "kernel": {
      "_type": "kernel",
      "execFormat": {
       "_type": "exec-format",
       "name": "elf"
      },
      "families": {},
      "name": "linux"
     }
    },
    {
     "kernel": {
      "families": {
       "darwin": {
        "_type": "exec-format",
        "name": "darwin"
       }
      }
     }
    }
   ],
   "position": "pkgs/development/python-modules/zope_exceptions/default.nix:22"
  },
  "revs": [
   "0000a86d7cd47005096a292a797d2e02ce29e8d8",
   "3b6ef967f3ff3f9c86ac0b406f2b1513f7b56c5c"
  ]
 },
 "4.4": {
  "meta": {
   "description": "Exception interfaces and implementations",
   "homepage": "https://pypi.python.org/pypi/zope.exceptions",
   "license": {
    "fullName": "Zope Public License 2.0",
    "shortName": "zpl20",
    "spdxId": "ZPL-2.0",
    "url": "https://spdx.org/licenses/ZPL-2.0.html"
   },
   "long_description": "",
   "maintainers": [
    {
     "email": "cillian.deroiste@gmail.com",
     "github": "cillianderoiste",
     "githubId": 643494,
     "name": "Cillian de R\u00f3iste"
    }
   ],
   "name": "python3.7-zope.exceptions",
   "platforms": [
    "aarch64-linux",
    "armv5tel-linux",
    "armv6l-linux",
    "armv7a-linux",
    "armv7l-linux",
    "mipsel-linux",
    "i686-linux",
    "x86_64-linux",
    "powerpc64le-linux",
    "riscv32-linux",
    "riscv64-linux",
    "x86_64-darwin",
    "i686-darwin",
    "aarch64-darwin",
    "armv7a-darwin"
   ],
   "position": "pkgs/development/python-modules/zope_exceptions/default.nix:22"
  },
  "revs": [
   "000404944c6da404f013111563bcc0084b270e28",
   "5101b357ec30c1ac4a9273b379e631f841af9fa3"
  ]
 }
}